export { default as App } from 'pages/App';
export { default as Vote} from 'pages/Vote';
export { default as Dashboard } from 'pages/Dashboard';
export { default as LoginOrRegister } from 'pages/LoginOrRegister';
export { default as About } from 'pages/About';
export { default as Test } from 'pages/Test';
export { default as Search } from 'pages/Search';
export { default as Film } from 'pages/Film';
export { default as User } from 'pages/User';
export { default as UserUpdate } from 'pages/UserUpdate';
export { default as AllUsers } from 'pages/AllUsers';
